#!/usr/bin/env python3
import sys

def hello(name):
    if (name == "batman") or (name == "robert"):
        print("Denever veszely")
    else:
        print("Hello " + name + "!" )

def main():
    name = sys.argv[1]
    hello(name)


if __name__ == "__main__":
    main()